# Default values for node.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  pullPolicy: IfNotPresent
service:
  name: node
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
resources:
  limits:
    cpu: 350m
    memory: 1000Mi
  requests:
    cpu: 150m
    memory: 250Mi
env:
  - name: 'DB_USER'
    value: 'root'
  - name: 'DB_PASSWORD'
    value: 'Mxc0TQ9r3U'
  - name: 'DB_HOST'
    value: 'altered-lizard-mysql'
ingress:
  enabled: true
  issuer: dev-issuer